name: CI Front

on:
  pull_request:
  merge_group:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  changed-files-check:
    if: github.event_name != 'merge_group'
    uses: ./.github/workflows/changed-files.yaml
    with:
      files: |
        package.json
        yarn.lock
        packages/twenty-front/**
        packages/twenty-ui/**
        packages/twenty-shared/**
        packages/twenty-sdk/**
        !packages/twenty-sdk/package.json
  front-task:
    needs: changed-files-check
    if: needs.changed-files-check.outputs.any_changed == 'true'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=4096'
      TASK_CACHE_KEY: front-task-${{ matrix.task }}
    strategy:
      matrix:
        task: [lint, typecheck, test]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Fetch custom Github Actions and base branch history
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Install dependencies
        uses: ./.github/actions/yarn-install
      - name: Restore ${{ matrix.task }} cache
        id: restore-task-cache
        uses: ./.github/actions/restore-cache
        with:
          key: ${{ env.TASK_CACHE_KEY }}
      - name: Reset .env
        uses: ./.github/actions/nx-affected
        with:
          tag: scope:frontend
          tasks: reset:env
      - name: Run ${{ matrix.task }} task
        id: run-task
        uses: ./.github/actions/nx-affected
        with:
          tag: scope:frontend
          tasks: ${{ matrix.task }}
      - name: Save ${{ matrix.task }} cache
        uses: ./.github/actions/save-cache
        with:
          key: ${{ steps.restore-task-cache.outputs.cache-primary-key }}
  front-build:
    needs: changed-files-check
    if: needs.changed-files-check.outputs.any_changed == 'true'
    timeout-minutes: 30
    runs-on: ubuntu-latest-8-cores
    env:
      NODE_OPTIONS: "--max-old-space-size=10240"
      ANALYZE: "true"
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Fetch custom Github Actions and base branch history
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Install dependencies
        uses: ./.github/actions/yarn-install
      - name: Front / Write .env
        run: npx nx reset:env twenty-front
      - name: Build frontend
        run: npx nx build twenty-front
      # - name: Upload frontend build artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: frontend-build
      #     path: packages/twenty-front/build
      #     retention-days: 1
  ci-front-status-check:
    if: always() && !cancelled()
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      [
        changed-files-check,
        front-task,
        front-build,
      ]
    steps:
      - name: Fail job if any needs failed
        if: contains(needs.*.result, 'failure')
        run: exit 1
